[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38', 'py39']
experimental_string_processing = true

[tool.isort]
profile = 'black'
multi_line_output = 3

[tool.pydocstyle]
ignore=['D105', 'D203', 'D213']
